### ISSUE TITLE
Создать необходимые объекты базы данных

### ISSUE THREAD

**Issue by zubrailx** [BD-term-paper/term-web-application#1]
#### Subtasks:
- [x] Создать скрипты для создания/удаления объектов базы данных
- [x] Обеспечить целостность данных при помощи средств языка DDL
- [x] Добавить триггеры для обеспечения комплексных ограничений целостности
    * Количество меню в кафе
    * Количество пунктов в меню
    * ~~Триггер логирования запросов (id, timestamp, func_type, description)~~ - бесполезно из-за избыточности и отсутствия преимуществ.
